doctrine:
    dbal:
        default_connection: default
        connections: 
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8mb4
            asl:
                # configure these for your database server
                url: '%env(resolve:DATABASE_ASL_URL)%'
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8mb4
            exploc:
                # configure these for your database server
                url: '%env(resolve:DATABASE_EXPLOC_URL)%'
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8mb4
            detr:
                # configure these for your database server
                url: '%env(resolve:DATABASE_DETR_URL)%'
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8mb4
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            asl:
                connection: asl
                mappings:
                    Asl:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Asl'
                        prefix: 'App\Entity\Asl'
                        alias: Asl
            exploc:
                connection: exploc
                mappings:
                    Exploc:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Exploc'
                        prefix: 'App\Entity\Exploc'
                        alias: Exploc
            detr:
                connection: detr
                mappings:
                    Detr:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Detr'
                        prefix: 'App\Entity\Detr'
                        alias: Detr